[package]
name = "gear"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
axum = "0.6.1"
diesel = { version = "2.0.2", features = ["postgres", "uuid"] }
diesel_migrations = "2.0.0"
once_cell = "1.16.0"
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4", "serde"] }

[profile.release]
codegen-units = 1
debug = 1
lto = true
